### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by wenche**

### CODE REVIEW

**Comment by wenche** [comment]
Are we really using ts-jest? Asking because it's commented out in jest.config.ts
`// preset: "ts-jest",`

**Comment by aronhoyer** [comment]
> Are we really using ts-jest?

i don't think we are

**Comment by wenche** [comment]
> > Are we really using ts-jest?
> 
> i don't think we are

Should we just remove it then? #bebrave

**Comment by aronhoyer** [comment]
yeah, i checked out next.js' [jest + react-testing-library example repo](https://github.com/vercel/next.js/tree/canary/examples/with-jest)—which also has typescript—and i can't see ts-jest in the dependency list. so i say we just remove it

**Comment by wenche** [comment]
Might be one of those things that comes out of the box with Next.js's jest support

**Review by aronhoyer — APPROVED** [review]

**Pull request merged**
