### PR TITLE
🔧 Prefer const for eslint

### PR DESCRIPTION
**Pull request by nilsml**
I think we should make it difficult to use let and var

### CODE REVIEW

**Review by wenche — APPROVED** [review]
LGTM 👍

**Comment by aronhoyer** [comment]
this rule is already set in `eslint-config-airbnb`

**Comment by nilsml** [comment]
I thought so too, but I don't see any warnings when using let. Perhaps change to error instead of warning 🤔

**Comment by aronhoyer** [comment]
eslint-config-airbnb has it set to error already (see https://github.com/airbnb/javascript/blob/366bfa66380c08304101c6add46355696e90b348/packages/eslint-config-airbnb-base/rules/es6.js#L115-L119)

**Comment by wenche** [comment]
I get this in my IDE. I don't know if no-mutable-exports is supposed to be a substitute or improvement to prefer-const, but I guess this is good enough for us? Close this PR?

Skjermbilde 2022-11-29 kl  13 13 11

**Comment by aronhoyer** [comment]
yeah, i think this pr is ripe for closing 👍

**Pull request closed without merging**
