### PR TITLE
fix: Fix bug where collibra search fails

### PR DESCRIPTION
**Pull request by aronhoyer**

### CODE REVIEW

**Review by wenche — APPROVED** [review]
I'm feeling lucky 😅

**Review by wenche — CHANGES_REQUESTED** [review]
When I test this locally,  I don't get any results back even with *

Skjermbilde 2023-02-08 kl  07 47 33

**Comment by aronhoyer** [comment]
@wenche should™ be fixed now

**Review by wenche — APPROVED** [review]
Can confirm!

**Pull request merged**
