### PR TITLE
Hiding See more from front page

### PR DESCRIPTION
**Pull request by ShikhaMishra9**

### CODE REVIEW

**Review by wenche — APPROVED** [review]
LGTM

**Comment by aronhoyer** [comment]
should we maybe remove it altogether? i don't want us to end up with commented out code all over the place :grimacing:

**Comment by ShikhaMishra9** [comment]
If there is no plan to have this feature added in front page then I am deleting it .

**Comment by aronhoyer** [comment]
> If there is no plan to have this feature added in front page then I am deleting it .

i wouldn't say it's probable that it gets re-introduced, but there is of course a chance that it might be. but this is such a small thing to implement, so i don't see any value in keeping it.

**Pull request merged**
